replicaCount: 2

image:
  repository: ecommercedevacr787.azurecr.io/order-service
  tag: "1.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

containerPort: 8000
environment: dev
