apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: user-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
