events {}

http {
    server {
        listen 8081;

        location /orders {
            proxy_pass http://order-service:8000;
        }

        location /users {
            proxy_pass http://user-service:8001;
        }

        location /payments {
            proxy_pass http://payment-service:8002;
        }

        location /health/order {
            proxy_pass http://order-service:8000/health;
        }

        location /health/user {
            proxy_pass http://user-service:8001/health;
        }

        location /health/payment {
            proxy_pass http://payment-service:8002/health;
        }
    }
}
