name: Order Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'services/order-service/**'
      - '.github/workflows/order-service-ci.yml'
      - '.github/workflows/reusable/microservice-ci.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'services/order-service/**'
      - '.github/workflows/order-service-ci.yml'
      - '.github/workflows/reusable/microservice-ci.yml'


jobs:
  microservice-ci:
    uses: ./.github/workflows/reusable/microservice-ci.yml

    with:
      service_name: order-service
      service_path: services/order-service
      dockerfile: services/order-service/Dockerfile
      image_repository: ecommercedevacr787.azurecr.io/order-service
      gitops_values_file: environments/dev/order-service-values.yaml

    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

    vars:
      APP_CLIENT_ID: ${{ vars.APP_CLIENT_ID }}
